__start__:
	doxygen Doxyfile 2> doxy.log
	@less -P " Dokumentacja w katalogu html. Aby zakonczyc nacisnij Q " doxy.log

clean:
	rm -fr html doxy.log

log:
	@less -P "  Dokumentacja w katalogu html. Aby zakonczyc nacisnij Q " doxy.log
